'use client'

import { useState, useRef, useEffect } from 'react'
import { ThemeProvider } from '@/components/theme-provider'
import { AuroraBackground } from '@/components/aurora-background'
import { NexusLogo } from '@/components/nexus-logo'
import { PromptBuilder } from '@/components/prompt-builder'
import {
  ArrowLeft, Monitor, Tablet, Smartphone, RefreshCw, ExternalLink,
  ChevronDown, ChevronUp, Brain, Layout, Code2, Database, Link2,
  TestTube2, Rocket, Check, X, Loader2, Sun, Moon,
  FileCode, FolderOpen, ChevronRight, Copy
} from 'lucide-react'
import { cn } from '@/lib/utils'
import Link from 'next/link'
import { useTheme } from '@/components/theme-provider'

type MessageRole = 'user' | 'assistant'
type PreviewDevice = 'desktop' | 'tablet' | 'mobile'
type PipelineStatus = 'waiting' | 'running' | 'done' | 'error'
type TabView = 'chat' | 'preview' | 'pipeline' | 'code'

interface Message {
  id: string
  role: MessageRole
  content: string
  timestamp: string
}

interface PipelineStep {
  id: string
  icon: React.ReactNode
  title: string
  desc: string
  status: PipelineStatus
}

const initialPipeline: PipelineStep[] = [
  { id: '1', icon: <Brain size={14} />, title: 'Understanding Request', desc: 'Analyzing your idea and requirements...', status: 'waiting' },
  { id: '2', icon: <Layout size={14} />, title: 'Planning Architecture', desc: 'Creating the application structure...', status: 'waiting' },
  { id: '3', icon: <Code2 size={14} />, title: 'Designing Interface', desc: 'Building UI components...', status: 'waiting' },
  { id: '4', icon: <Database size={14} />, title: 'Creating Backend', desc: 'Generating database and logic...', status: 'waiting' },
  { id: '5', icon: <Link2 size={14} />, title: 'Connecting Services', desc: 'Preparing integrations...', status: 'waiting' },
  { id: '6', icon: <TestTube2 size={14} />, title: 'Testing Application', desc: 'Checking quality...', status: 'waiting' },
  { id: '7', icon: <Rocket size={14} />, title: 'Deploying', desc: 'Preparing production version...', status: 'waiting' },
]

const mockAIResponses = [
  `I'll build this for you right away. Let me analyze your requirements and create a comprehensive architecture plan.\n\n**Here's what I'll generate:**\n- Next.js 15 frontend with TypeScript\n- Tailwind CSS for styling\n- Authentication with JWT sessions\n- PostgreSQL database with Drizzle ORM\n- REST API endpoints\n- Deployment configuration\n\nStarting the build pipeline now...`,
  `I've completed the initial generation. Here's a summary of what was built:\n\n**Frontend**\n- 8 pages including dashboard, auth, and settings\n- Responsive design for all screen sizes\n- Dark/light mode support\n\n**Backend**\n- 12 API routes\n- User authentication system\n- Database schema with 6 tables\n\nThe live preview is ready. What would you like to change?`,
]

const sampleCode = `// Generated by Nexus AI
import { db } from '@/lib/db'
import { auth } from '@/lib/auth'

export async function GET(request: Request) {
  const session = await auth.getSession(request)
  if (!session) return new Response('Unauthorized', { status: 401 })
  
  const projects = await db
    .select()
    .from(projectsTable)
    .where(eq(projectsTable.userId, session.user.id))
    .orderBy(desc(projectsTable.createdAt))
  
  return Response.json({ projects })
}`

const fileTree = [
  { name: 'src', type: 'folder', items: [
    { name: 'app', type: 'folder', items: [
      { name: 'page.tsx', type: 'file' },
      { name: 'layout.tsx', type: 'file' },
      { name: 'api', type: 'folder', items: [
        { name: 'projects', type: 'folder', items: [
          { name: 'route.ts', type: 'file' },
        ]},
      ]},
    ]},
    { name: 'components', type: 'folder', items: [
      { name: 'ui', type: 'folder', items: [] },
    ]},
    { name: 'lib', type: 'folder', items: [
      { name: 'db.ts', type: 'file' },
      { name: 'auth.ts', type: 'file' },
    ]},
  ]},
]

function WorkspaceInner() {
  const { theme, toggleTheme } = useTheme()
  const [messages, setMessages] = useState<Message[]>([
    { id: '1', role: 'assistant', content: 'Hello! I\'m your AI software engineer. Describe the app you want to build and I\'ll generate it for you. I can build full-stack applications, plan architecture, or discuss your ideas.', timestamp: 'now' }
  ])
  const [pipeline, setPipeline] = useState(initialPipeline)
  const [pipelineOpen, setPipelineOpen] = useState(false)
  const [previewDevice, setPreviewDevice] = useState<PreviewDevice>('desktop')
  const [previewState, setPreviewState] = useState<'empty' | 'loading' | 'live'>('empty')
  const [isGenerating, setIsGenerating] = useState(false)
  const [activeTab, setActiveTab] = useState<TabView>('chat')
  const [deployOpen, setDeployOpen] = useState(false)
  const [deployStep, setDeployStep] = useState(0)
  const [deployDone, setDeployDone] = useState(false)
  const [codeView, setCodeView] = useState('api/projects/route.ts')
  const messagesEndRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages])

  const runPipeline = async () => {
    setPreviewState('loading')
    const steps = [...initialPipeline]
    for (let i = 0; i < steps.length; i++) {
      steps[i] = { ...steps[i], status: 'running' }
      setPipeline([...steps])
      await new Promise(r => setTimeout(r, 700))
      steps[i] = { ...steps[i], status: 'done' }
      setPipeline([...steps])
    }
    setPreviewState('live')
    setIsGenerating(false)
  }

  const handleSend = async (text: string) => {
    const userMsg: Message = { id: Date.now().toString(), role: 'user', content: text, timestamp: 'just now' }
    setMessages(p => [...p, userMsg])
    setIsGenerating(true)
    setPipelineOpen(true)

    await new Promise(r => setTimeout(r, 800))

    // Stream AI response
    const responseText = mockAIResponses[messages.length > 1 ? 1 : 0]
    const aiMsg: Message = { id: (Date.now() + 1).toString(), role: 'assistant', content: '', timestamp: 'just now' }
    setMessages(p => [...p, aiMsg])

    let i = 0
    const interval = setInterval(() => {
      i += 4
      setMessages(p => p.map(m => m.id === aiMsg.id ? { ...m, content: responseText.slice(0, i) } : m))
      if (i >= responseText.length) {
        clearInterval(interval)
        runPipeline()
      }
    }, 30)
  }

  const handleDeploy = async () => {
    setDeployOpen(true)
    setDeployStep(0)
    setDeployDone(false)
    const steps = 4
    for (let i = 0; i <= steps; i++) {
      await new Promise(r => setTimeout(r, 800))
      setDeployStep(i)
    }
    setDeployDone(true)
  }

  const deviceWidths: Record<PreviewDevice, string> = {
    desktop: '100%',
    tablet: '768px',
    mobile: '375px',
  }

  const statusColors: Record<PipelineStatus, string> = {
    waiting: 'var(--muted-foreground)',
    running: 'var(--nexus-cyan)',
    done: 'oklch(0.72 0.16 150)',
    error: 'var(--destructive)',
  }

  const tabs: { id: TabView; label: string }[] = [
    { id: 'chat', label: 'Chat' },
    { id: 'preview', label: 'Preview' },
    { id: 'pipeline', label: 'Pipeline' },
    { id: 'code', label: 'Code' },
  ]

  const formatMessage = (content: string) => {
    return content.split('\n').map((line, i) => {
      if (line.startsWith('**') && line.endsWith('**')) {
        return <p key={i} className="font-semibold text-foreground mt-3 mb-1">{line.replace(/\*\*/g, '')}</p>
      }
      if (line.startsWith('- ')) {
        return <li key={i} className="text-muted-foreground text-sm ml-3">{line.slice(2)}</li>
      }
      return line ? <p key={i} className="text-sm text-muted-foreground leading-relaxed">{line}</p> : <div key={i} className="h-1" />
    })
  }

  return (
    <AuroraBackground className="flex flex-col h-screen overflow-hidden">
      {/* Top bar */}
      <header className="flex-shrink-0 glass border-b border-white/8 px-4 py-2.5 flex items-center gap-3 z-20">
        <Link href="/dashboard" className="p-1.5 rounded-lg glass-card-sm text-muted-foreground hover:text-foreground transition-all">
          <ArrowLeft size={14} />
        </Link>
        <NexusLogo size="sm" showText />
        <div className="h-4 w-px bg-white/15" />
        <div className="flex items-center gap-2">
          <div className="w-2 h-2 rounded-full animate-pulse" style={{ background: isGenerating ? 'var(--nexus-cyan)' : previewState === 'live' ? 'oklch(0.72 0.16 150)' : 'var(--muted-foreground)' }} />
          <span className="text-xs text-muted-foreground">
            {isGenerating ? 'Building...' : previewState === 'live' ? 'Ready' : 'Workspace'}
          </span>
        </div>
        <div className="flex-1" />
        {/* Project actions */}
        <div className="hidden sm:flex items-center gap-1.5">
          {['Save', 'Rename', 'Duplicate'].map(a => (
            <button key={a} className="px-2.5 py-1 glass-card-sm text-xs text-muted-foreground hover:text-foreground transition-all rounded-lg">
              {a}
            </button>
          ))}
          <button
            onClick={handleDeploy}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold transition-all hover:scale-105 nexus-glow"
            style={{ background: 'linear-gradient(135deg, var(--nexus-cyan), var(--nexus-blue))', color: 'oklch(0.1 0.015 240)' }}
          >
            <Rocket size={12} />Deploy
          </button>
        </div>
        <button
          onClick={toggleTheme}
          className="p-1.5 rounded-lg glass-card-sm text-muted-foreground hover:text-foreground transition-all"
        >
          {theme === 'dark' ? <Sun size={13} /> : <Moon size={13} />}
        </button>
      </header>

      {/* Mobile tabs */}
      <div className="lg:hidden flex glass border-b border-white/8 px-4">
        {tabs.map(t => (
          <button
            key={t.id}
            onClick={() => setActiveTab(t.id)}
            className={cn(
              'flex-1 py-2.5 text-xs font-medium transition-all border-b-2 -mb-px',
              activeTab === t.id ? 'border-[var(--nexus-cyan)] text-foreground' : 'border-transparent text-muted-foreground'
            )}
          >
            {t.label}
          </button>
        ))}
      </div>

      {/* Main split */}
      <div className="flex flex-1 min-h-0">

        {/* LEFT: Chat panel */}
        <div className={cn(
          'flex flex-col border-r border-white/8 glass-strong',
          'lg:w-[420px] lg:flex',
          activeTab === 'chat' ? 'flex flex-1' : 'hidden',
          'lg:flex-none'
        )}>
          {/* Messages */}
          <div className="flex-1 overflow-y-auto p-4 space-y-4">
            {messages.map(msg => (
              <div key={msg.id} className={cn('flex gap-3', msg.role === 'user' && 'flex-row-reverse')}>
                {/* Avatar */}
                <div
                  className="w-7 h-7 rounded-full flex-shrink-0 flex items-center justify-center text-xs font-medium"
                  style={
                    msg.role === 'assistant'
                      ? { background: 'linear-gradient(135deg, var(--nexus-cyan)/20, var(--nexus-blue)/20)', color: 'var(--nexus-cyan)', border: '1px solid var(--nexus-cyan)/20' }
                      : { background: 'linear-gradient(135deg, var(--nexus-cyan), var(--nexus-blue))', color: 'oklch(0.1 0.015 240)' }
                  }
                >
                  {msg.role === 'assistant' ? 'N' : 'U'}
                </div>
                {/* Bubble */}
                <div className={cn(
                  'glass-card-sm px-3.5 py-3 max-w-[85%] text-sm',
                  msg.role === 'user' ? 'rounded-br-sm' : 'rounded-bl-sm'
                )}>
                  {msg.role === 'assistant' ? (
                    <div>
                      {msg.content ? formatMessage(msg.content) : (
                        <div className="flex items-center gap-1 py-0.5">
                          <span className="typing-dot w-1.5 h-1.5 rounded-full bg-muted-foreground" />
                          <span className="typing-dot w-1.5 h-1.5 rounded-full bg-muted-foreground" />
                          <span className="typing-dot w-1.5 h-1.5 rounded-full bg-muted-foreground" />
                        </div>
                      )}
                    </div>
                  ) : (
                    <p className="text-sm">{msg.content}</p>
                  )}
                </div>
              </div>
            ))}
            <div ref={messagesEndRef} />
          </div>

          {/* Pipeline bar */}
          <div className="border-t border-white/8">
            <button
              onClick={() => setPipelineOpen(!pipelineOpen)}
              className="w-full flex items-center justify-between px-4 py-2.5 text-xs text-muted-foreground hover:text-foreground transition-colors"
            >
              <span className="flex items-center gap-2">
                <span
                  className="w-1.5 h-1.5 rounded-full"
                  style={{ background: isGenerating ? 'var(--nexus-cyan)' : previewState === 'live' ? 'oklch(0.72 0.16 150)' : 'var(--muted-foreground)' }}
                />
                Build Pipeline
                {isGenerating && <Loader2 size={10} className="animate-spin" style={{ color: 'var(--nexus-cyan)' }} />}
              </span>
              {pipelineOpen ? <ChevronDown size={12} /> : <ChevronUp size={12} />}
            </button>
            {pipelineOpen && (
              <div className="px-3 pb-3 space-y-1">
                {pipeline.map(step => (
                  <div key={step.id} className="flex items-center gap-2.5 py-1.5 px-2 rounded-lg hover:bg-white/5 transition-colors">
                    <span style={{ color: statusColors[step.status] }}>
                      {step.status === 'running' ? <Loader2 size={13} className="animate-spin" /> : step.icon}
                    </span>
                    <span className={cn('text-xs flex-1', step.status === 'waiting' && 'text-muted-foreground/50')}>
                      {step.title}
                    </span>
                    {step.status === 'done' && <Check size={11} style={{ color: 'oklch(0.72 0.16 150)' }} />}
                    {step.status === 'error' && <X size={11} style={{ color: 'var(--destructive)' }} />}
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Prompt input */}
          <div className="p-3 border-t border-white/8">
            <PromptBuilder compact onSubmit={handleSend} />
          </div>
        </div>

        {/* RIGHT: Preview + Code tabs */}
        <div className={cn(
          'flex-1 flex flex-col min-w-0',
          activeTab !== 'chat' && activeTab !== 'pipeline' ? 'flex' : 'hidden lg:flex'
        )}>
          {/* Preview / Code tabs */}
          <div className="flex items-center gap-1 px-3 py-2 border-b border-white/8 glass flex-shrink-0">
            {['Preview', 'Code'].map(t => (
              <button
                key={t}
                onClick={() => setActiveTab(t.toLowerCase() as TabView)}
                className={cn(
                  'px-3 py-1 rounded-lg text-xs font-medium transition-all',
                  (activeTab === t.toLowerCase() || (activeTab === 'chat' && t === 'Preview'))
                    ? 'text-foreground'
                    : 'text-muted-foreground hover:text-foreground'
                )}
                style={(activeTab === t.toLowerCase()) ? { background: 'var(--nexus-cyan)/15', color: 'var(--nexus-cyan)' } : {}}
              >
                {t}
              </button>
            ))}
            <div className="flex-1" />
            {/* Device controls */}
            <div className="flex items-center gap-1">
              {([['desktop', Monitor], ['tablet', Tablet], ['mobile', Smartphone]] as [PreviewDevice, React.ElementType][]).map(([d, Icon]) => (
                <button
                  key={d}
                  onClick={() => setPreviewDevice(d)}
                  className={cn(
                    'p-1.5 rounded-lg transition-all',
                    previewDevice === d ? '' : 'text-muted-foreground hover:text-foreground hover:bg-white/8'
                  )}
                  style={previewDevice === d ? { color: 'var(--nexus-cyan)', background: 'var(--nexus-cyan)/10' } : {}}
                >
                  <Icon size={13} />
                </button>
              ))}
              <div className="w-px h-4 bg-white/10 mx-1" />
              <button className="p-1.5 rounded-lg text-muted-foreground hover:text-foreground hover:bg-white/8 transition-all">
                <RefreshCw size={13} />
              </button>
              <button className="p-1.5 rounded-lg text-muted-foreground hover:text-foreground hover:bg-white/8 transition-all">
                <ExternalLink size={13} />
              </button>
            </div>
          </div>

          {/* Preview area */}
          {activeTab !== 'code' && (
            <div className="flex-1 overflow-auto flex items-start justify-center p-4">
              <div
                className="h-full glass-card overflow-hidden transition-all duration-500 flex flex-col"
                style={{ width: deviceWidths[previewDevice], maxWidth: '100%', minHeight: '100%' }}
              >
                {/* Browser chrome */}
                <div className="flex items-center gap-2 px-3 py-2.5 border-b border-white/8 flex-shrink-0">
                  <div className="flex gap-1.5">
                    {['#f87171', '#fbbf24', '#4ade80'].map(c => (
                      <div key={c} className="w-2.5 h-2.5 rounded-full" style={{ background: c }} />
                    ))}
                  </div>
                  <div className="flex-1 glass-card-sm px-3 py-1 text-[11px] text-muted-foreground/60 rounded-lg text-center">
                    app.nexus.preview
                  </div>
                </div>

                {/* Content */}
                <div className="flex-1 flex items-center justify-center">
                  {previewState === 'empty' && (
                    <div className="text-center p-8">
                      <Monitor size={32} className="mx-auto mb-3 text-muted-foreground/30" />
                      <p className="text-sm text-muted-foreground/60">Your generated app will appear here.</p>
                      <p className="text-xs text-muted-foreground/40 mt-1">Describe your idea in the chat to get started.</p>
                    </div>
                  )}
                  {previewState === 'loading' && (
                    <div className="text-center p-8 space-y-4">
                      <Loader2 size={28} className="mx-auto animate-spin" style={{ color: 'var(--nexus-cyan)' }} />
                      <div>
                        <p className="text-sm font-medium" style={{ color: 'var(--nexus-cyan)' }}>Building your application</p>
                        <div className="flex justify-center gap-1 mt-3">
                          {pipeline.filter(s => s.status === 'running').map(s => (
                            <span key={s.id} className="text-xs text-muted-foreground">{s.title}...</span>
                          ))}
                        </div>
                      </div>
                    </div>
                  )}
                  {previewState === 'live' && (
                    <div className="w-full h-full p-6 space-y-4 overflow-y-auto">
                      {/* Mock generated app preview */}
                      <div className="glass-card p-4">
                        <div className="flex items-center justify-between mb-4">
                          <div className="flex items-center gap-2">
                            <div className="w-2 h-2 rounded-full" style={{ background: 'var(--nexus-cyan)' }} />
                            <span className="text-sm font-semibold">Generated App Preview</span>
                          </div>
                          <span className="px-2 py-0.5 rounded-full text-[11px]" style={{ background: 'oklch(0.72 0.16 150)/15', color: 'oklch(0.72 0.16 150)' }}>Live</span>
                        </div>
                        <div className="grid grid-cols-3 gap-3 mb-4">
                          {[['Total Users', '2,847'], ['Revenue', '$12.4k'], ['Active', '94%']].map(([l, v]) => (
                            <div key={l} className="glass-card-sm p-3 text-center">
                              <div className="text-lg font-bold text-gradient-cyan">{v}</div>
                              <div className="text-[11px] text-muted-foreground">{l}</div>
                            </div>
                          ))}
                        </div>
                        <div className="glass-card-sm p-3">
                          <div className="text-xs font-medium mb-2">Recent Activity</div>
                          {['User signed up', 'Payment processed', 'Report generated'].map((a, i) => (
                            <div key={a} className="flex items-center gap-2 py-1.5 border-b border-white/5 last:border-0">
                              <div className="w-1.5 h-1.5 rounded-full" style={{ background: 'var(--nexus-cyan)' }} />
                              <span className="text-xs text-muted-foreground">{a}</span>
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              </div>
            </div>
          )}

          {/* Code view */}
          {activeTab === 'code' && (
            <div className="flex-1 flex min-h-0">
              {/* File tree */}
              <div className="w-44 flex-shrink-0 border-r border-white/8 p-2 overflow-y-auto">
                <p className="text-[10px] text-muted-foreground uppercase tracking-wider px-2 mb-2">Files</p>
                {[
                  'app/page.tsx', 'app/layout.tsx',
                  'api/projects/route.ts', 'api/auth/route.ts',
                  'components/ui/button.tsx', 'lib/db.ts', 'lib/auth.ts',
                ].map(f => (
                  <button
                    key={f}
                    onClick={() => setCodeView(f)}
                    className={cn(
                      'w-full flex items-center gap-1.5 px-2 py-1.5 rounded-lg text-[11px] text-left transition-all',
                      codeView === f ? 'text-foreground' : 'text-muted-foreground hover:text-foreground hover:bg-white/6'
                    )}
                    style={codeView === f ? { background: 'var(--nexus-cyan)/10', color: 'var(--nexus-cyan)' } : {}}
                  >
                    <FileCode size={10} />{f.split('/').pop()}
                  </button>
                ))}
              </div>
              {/* Code editor */}
              <div className="flex-1 p-4 overflow-auto">
                <div className="flex items-center justify-between mb-3">
                  <span className="text-xs text-muted-foreground">{codeView}</span>
                  <button className="p-1.5 rounded-lg glass-card-sm text-muted-foreground hover:text-foreground transition-all">
                    <Copy size={11} />
                  </button>
                </div>
                <pre className="font-mono text-xs leading-relaxed text-foreground/80 whitespace-pre-wrap">
                  {sampleCode}
                </pre>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Deploy Modal */}
      {deployOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
          <div className="glass-card p-6 w-full max-w-sm">
            <h3 className="text-base font-semibold mb-4">Deploying Application</h3>
            <div className="space-y-3 mb-5">
              {['Preparing build', 'Checking errors', 'Deploying', 'Creating URL'].map((s, i) => (
                <div key={s} className="flex items-center gap-3">
                  <div className="w-5 h-5 rounded-full flex items-center justify-center flex-shrink-0">
                    {deployStep > i ? (
                      <Check size={11} style={{ color: 'oklch(0.72 0.16 150)' }} />
                    ) : deployStep === i ? (
                      <Loader2 size={11} className="animate-spin" style={{ color: 'var(--nexus-cyan)' }} />
                    ) : (
                      <div className="w-1.5 h-1.5 rounded-full bg-muted-foreground/30" />
                    )}
                  </div>
                  <span className={cn('text-sm', deployStep <= i && 'text-muted-foreground/50')}>{s}</span>
                </div>
              ))}
            </div>
            {deployDone ? (
              <div className="space-y-3">
                <div
                  className="glass-card-sm px-4 py-3 text-center"
                  style={{ border: '1px solid oklch(0.72 0.16 150)/20', background: 'oklch(0.72 0.16 150)/5' }}
                >
                  <p className="text-xs text-muted-foreground mb-1">Your app is live at</p>
                  <p className="text-sm font-medium" style={{ color: 'oklch(0.72 0.16 150)' }}>my-project.nexus.app</p>
                </div>
                <div className="flex gap-2">
                  <button className="flex-1 py-2 rounded-xl glass-card-sm text-sm text-muted-foreground hover:text-foreground transition-all">
                    Share
                  </button>
                  <button
                    onClick={() => { setDeployOpen(false); setDeployDone(false); setDeployStep(0) }}
                    className="flex-1 py-2 rounded-xl text-sm font-medium transition-all"
                    style={{ background: 'linear-gradient(135deg, var(--nexus-cyan), var(--nexus-blue))', color: 'oklch(0.1 0.015 240)' }}
                  >
                    Done
                  </button>
                </div>
              </div>
            ) : (
              <button
                onClick={() => { setDeployOpen(false); setDeployStep(0) }}
                className="w-full py-2 rounded-xl glass-card-sm text-sm text-muted-foreground hover:text-foreground transition-all"
              >
                Cancel
              </button>
            )}
          </div>
        </div>
      )}
    </AuroraBackground>
  )
}

export default function WorkspacePage() {
  return (
    <ThemeProvider>
      <WorkspaceInner />
    </ThemeProvider>
  )
}
